import enum
from datetime import date, datetime, timezone
from decimal import Decimal
from sqlalchemy import Boolean, Date, DateTime, Enum, ForeignKey, Numeric, String, Text, JSON, Table, Column, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.database.session import Base

def now(): return datetime.now(timezone.utc)
class RoleName(str,enum.Enum):
 SYSTEM_ADMIN="System Admin"; BID_MANAGER="Bid Manager"; PROPOSAL_ENGINEER="Proposal Engineer"; PLANNING="Planning"; ENGINEERING="Engineering"; CONTRACTS="Contracts"; COMMERCIAL="Commercial"; PROCUREMENT="Procurement"; FINANCE="Finance"; MANAGEMENT_REVIEWER="Management Reviewer"; READ_ONLY="Read Only"
user_roles=Table("user_roles",Base.metadata,Column("user_id",ForeignKey("users.id",ondelete="CASCADE"),primary_key=True),Column("role_id",ForeignKey("roles.id",ondelete="CASCADE"),primary_key=True))
class Role(Base):
 __tablename__="roles"; id:Mapped[int]=mapped_column(primary_key=True); name:Mapped[RoleName]=mapped_column(Enum(RoleName),unique=True,nullable=False)
class User(Base):
 __tablename__="users"; id:Mapped[int]=mapped_column(primary_key=True); email:Mapped[str]=mapped_column(String(255),unique=True,index=True); full_name:Mapped[str]=mapped_column(String(255)); is_active:Mapped[bool]=mapped_column(Boolean,default=True); roles:Mapped[list[Role]]=relationship(secondary=user_roles,lazy="selectin")
class BidProject(Base):
 __tablename__="bid_projects"; id:Mapped[int]=mapped_column(primary_key=True); bid_id:Mapped[str]=mapped_column(String(50),unique=True,index=True); tender_reference_no:Mapped[str]=mapped_column(String(100)); client:Mapped[str]=mapped_column(String(200)); tender_name:Mapped[str]=mapped_column(String(300)); contract_type:Mapped[str]=mapped_column(String(80)); project_type:Mapped[str]=mapped_column(String(100)); package_section:Mapped[str|None]=mapped_column(String(200)); location:Mapped[str|None]=mapped_column(String(200)); estimated_value:Mapped[Decimal|None]=mapped_column(Numeric(18,2)); currency:Mapped[str]=mapped_column(String(3),default="INR"); tender_due_date:Mapped[date]=mapped_column(Date); pre_bid_meeting_date:Mapped[date|None]=mapped_column(Date); bid_manager:Mapped[str]=mapped_column(String(200)); co_bid_manager:Mapped[str|None]=mapped_column(String(200)); current_stage:Mapped[str]=mapped_column(String(80),default="Opportunity"); bid_status:Mapped[str]=mapped_column(String(40),default="Draft"); description:Mapped[str|None]=mapped_column(Text); created_by:Mapped[int]=mapped_column(ForeignKey("users.id")); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now)
class ProjectMembership(Base):
 __tablename__="project_memberships"; __table_args__=(UniqueConstraint("bid_project_id","user_id",name="uq_project_member"),); id:Mapped[int]=mapped_column(primary_key=True); bid_project_id:Mapped[int]=mapped_column(ForeignKey("bid_projects.id",ondelete="CASCADE"),index=True); user_id:Mapped[int]=mapped_column(ForeignKey("users.id",ondelete="CASCADE"),index=True); role:Mapped[str]=mapped_column(String(50))
class BidDocument(Base):
 __tablename__="bid_documents"; id:Mapped[int]=mapped_column(primary_key=True); bid_project_id:Mapped[int]=mapped_column(ForeignKey("bid_projects.id",ondelete="CASCADE"),index=True); original_filename:Mapped[str]=mapped_column(String(255)); stored_filename:Mapped[str|None]=mapped_column(String(255)); file_extension:Mapped[str]=mapped_column(String(12),index=True); mime_type:Mapped[str]=mapped_column(String(150)); file_size:Mapped[int]=mapped_column(); checksum:Mapped[str]=mapped_column(String(64),index=True); storage_path:Mapped[str|None]=mapped_column(String(500)); uploaded_by:Mapped[int]=mapped_column(ForeignKey("users.id")); uploader:Mapped[User]=relationship(); uploaded_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,index=True); document_status:Mapped[str]=mapped_column(String(40),default="Needs Review",index=True); document_category:Mapped[str|None]=mapped_column(String(100),index=True); document_type:Mapped[str|None]=mapped_column(String(100)); document_number:Mapped[str|None]=mapped_column(String(100)); document_title:Mapped[str|None]=mapped_column(String(300)); revision:Mapped[str|None]=mapped_column(String(50)); document_date:Mapped[date|None]=mapped_column(Date); classification_status:Mapped[str|None]=mapped_column(String(40),default="pending",index=True); classification_confidence:Mapped[Decimal|None]=mapped_column(Numeric(5,4)); is_latest_version:Mapped[bool|None]=mapped_column(Boolean,default=True); remarks:Mapped[str|None]=mapped_column(Text); document_subcategory:Mapped[str|None]=mapped_column(String(100)); information_tags:Mapped[list]=mapped_column(JSON,default=list); revision_no:Mapped[int]=mapped_column(default=1); is_latest_revision:Mapped[bool]=mapped_column(Boolean,default=True); revision_of_document_id:Mapped[int|None]=mapped_column(ForeignKey("bid_documents.id")); duplicate_of_document_id:Mapped[int|None]=mapped_column(ForeignKey("bid_documents.id")); source_type:Mapped[str]=mapped_column(String(50),default="Tender Upload"); notes:Mapped[str|None]=mapped_column(Text)
 @property
 def uploader_name(self): return self.uploader.full_name if self.uploader else None
class BidRequirement(Base):
 __tablename__="bid_requirements"
 id:Mapped[int]=mapped_column(primary_key=True); bid_project_id:Mapped[int]=mapped_column(ForeignKey("bid_projects.id",ondelete="CASCADE"),index=True); source_document_id:Mapped[int|None]=mapped_column(ForeignKey("bid_documents.id",ondelete="SET NULL"),index=True); source_document:Mapped[BidDocument|None]=relationship(); requirement_category:Mapped[str]=mapped_column(String(100),index=True); requirement_type:Mapped[str|None]=mapped_column(String(100)); requirement_title:Mapped[str]=mapped_column(String(300)); requirement_text:Mapped[str]=mapped_column(Text); source_page:Mapped[str|None]=mapped_column(String(50)); source_clause:Mapped[str|None]=mapped_column(String(100)); source_section:Mapped[str|None]=mapped_column(String(200)); source_excerpt:Mapped[str|None]=mapped_column(Text); responsible_function:Mapped[str|None]=mapped_column(String(100)); responsible_person:Mapped[str|None]=mapped_column(String(200)); due_date:Mapped[date|None]=mapped_column(Date,index=True); priority:Mapped[str]=mapped_column(String(20),default="Medium",index=True); requirement_status:Mapped[str]=mapped_column(String(40),default="Open",index=True); is_mandatory:Mapped[bool]=mapped_column(Boolean,default=False); compliance_status:Mapped[str]=mapped_column(String(40),default="Not Assessed"); review_status:Mapped[str]=mapped_column(String(40),default="Not Reviewed"); reviewed_by:Mapped[int|None]=mapped_column(ForeignKey("users.id")); reviewed_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); extraction_method:Mapped[str]=mapped_column(String(40),default="Manual"); extraction_confidence:Mapped[Decimal|None]=mapped_column(Numeric(5,4)); created_by:Mapped[int]=mapped_column(ForeignKey("users.id")); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now); notes:Mapped[str|None]=mapped_column(Text)
 @property
 def source_original_filename(self): return self.source_document.original_filename if self.source_document else None
 @property
 def source_document_title(self): return self.source_document.document_title if self.source_document else None
 @property
 def source_document_category(self): return self.source_document.document_category if self.source_document else None
class BidMissingInput(Base):
 __tablename__="bid_missing_inputs"
 id:Mapped[int]=mapped_column(primary_key=True); bid_project_id:Mapped[int]=mapped_column(ForeignKey("bid_projects.id",ondelete="CASCADE"),index=True); requirement_id:Mapped[int|None]=mapped_column(ForeignKey("bid_requirements.id",ondelete="SET NULL"),index=True); requirement:Mapped[BidRequirement|None]=relationship(); source_document_id:Mapped[int|None]=mapped_column(ForeignKey("bid_documents.id",ondelete="SET NULL"),index=True); source_document:Mapped[BidDocument|None]=relationship(); missing_input_title:Mapped[str]=mapped_column(String(300)); missing_input_description:Mapped[str]=mapped_column(Text); input_category:Mapped[str]=mapped_column(String(100)); input_type:Mapped[str]=mapped_column(String(100)); responsible_function:Mapped[str|None]=mapped_column(String(100),index=True); responsible_person:Mapped[str|None]=mapped_column(String(200)); requested_from:Mapped[str|None]=mapped_column(String(200)); required_by_date:Mapped[date|None]=mapped_column(Date,index=True); priority:Mapped[str]=mapped_column(String(20),default="Medium",index=True); status:Mapped[str]=mapped_column(String(40),default="Open",index=True); impact_if_missing:Mapped[str|None]=mapped_column(Text); resolution_notes:Mapped[str|None]=mapped_column(Text); source_page:Mapped[str|None]=mapped_column(String(50)); source_clause:Mapped[str|None]=mapped_column(String(100)); source_section:Mapped[str|None]=mapped_column(String(200)); source_excerpt:Mapped[str|None]=mapped_column(Text); created_by:Mapped[int]=mapped_column(ForeignKey("users.id")); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now); resolved_by:Mapped[int|None]=mapped_column(ForeignKey("users.id")); resolved_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
 @property
 def requirement_title(self): return self.requirement.requirement_title if self.requirement else None
 @property
 def requirement_category(self): return self.requirement.requirement_category if self.requirement else None
 @property
 def requirement_status(self): return self.requirement.requirement_status if self.requirement else None
 @property
 def source_original_filename(self): return self.source_document.original_filename if self.source_document else None
 @property
 def source_document_title(self): return self.source_document.document_title if self.source_document else None
class AuditEvent(Base):
 __tablename__="audit_events"; id:Mapped[int]=mapped_column(primary_key=True); user_id:Mapped[int|None]=mapped_column(ForeignKey("users.id")); user:Mapped[User|None]=relationship(); bid_project_id:Mapped[int|None]=mapped_column(ForeignKey("bid_projects.id"),index=True); event_type:Mapped[str]=mapped_column(String(80),index=True); entity_type:Mapped[str]=mapped_column(String(80)); entity_id:Mapped[str]=mapped_column(String(80)); timestamp:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,index=True); request_metadata:Mapped[dict]=mapped_column(JSON,default=dict); details:Mapped[dict]=mapped_column(JSON,default=dict)
