export type Bid={id:number;bid_id:string;tender_reference_no:string;tender_name:string;client:string;location?:string|null;contract_type:string;project_type:string;tender_due_date:string;current_stage:string;bid_status:string;bid_manager:string;updated_at:string};
export type Document={
  id:number;bid_project_id:number;original_filename:string;file_extension:string;mime_type:string;file_size:number;checksum:string;
  uploaded_by:number;uploader_name:string|null;uploaded_at:string;document_status:string;document_category:string|null;
  document_type:string|null;document_number:string|null;document_title:string|null;revision:string|null;document_date:string|null;
  classification_status:"pending"|"classified"|"needs_review"|"manually_classified"|null;
  classification_confidence:number|null;is_latest_version:boolean|null;remarks:string|null;
  document_subcategory:string|null;information_tags:string[];revision_no:number;is_latest_revision:boolean;
  revision_of_document_id:number|null;duplicate_of_document_id:number|null;notes:string|null;
};
export type Page<T>={items:T[];total:number;page:number;page_size:number};
export type Requirement={id:number;bid_project_id:number;source_document_id:number|null;requirement_category:string;requirement_type:string|null;requirement_title:string;requirement_text:string;source_page:string|null;source_clause:string|null;source_section:string|null;source_excerpt:string|null;responsible_function:string|null;responsible_person:string|null;due_date:string|null;priority:string;requirement_status:string;is_mandatory:boolean;compliance_status:string;review_status:string;reviewed_by:number|null;reviewed_at:string|null;extraction_method:string;extraction_confidence:number|null;created_by:number;created_at:string;updated_at:string;notes:string|null;source_original_filename:string|null;source_document_title:string|null;source_document_category:string|null};
export type RequirementPage=Page<Requirement>&{summary:{total:number;critical:number;open:number;needs_review:number;non_compliant:number}};
export type RequirementExtractionSummary={document_id:number;created:number;skipped_duplicates:number;low_confidence_skipped:number;no_text:boolean;extractor_version:string};
export type MissingInput={id:number;bid_project_id:number;requirement_id:number|null;source_document_id:number|null;missing_input_title:string;missing_input_description:string;input_category:string;input_type:string;responsible_function:string|null;responsible_person:string|null;requested_from:string|null;required_by_date:string|null;priority:string;status:string;impact_if_missing:string|null;resolution_notes:string|null;source_page:string|null;source_clause:string|null;source_section:string|null;source_excerpt:string|null;created_by:number;created_at:string;updated_at:string;resolved_by:number|null;resolved_at:string|null;requirement_title:string|null;requirement_category:string|null;requirement_status:string|null;source_original_filename:string|null;source_document_title:string|null};
export type MissingInputPage=Page<MissingInput>&{summary:{total:number;critical:number;open:number;overdue:number;requested:number;resolved:number}};
export type EstimationReadiness={overall_score:number;grade:string;components:{information_completeness:number;review_completion:number;compliance_assessment:number;blocker_control:number};counts:{active_requirements:number;requirements_with_open_gaps:number;open_missing_inputs:number;critical_open:number;high_open:number;overdue:number;candidate_gaps:number};candidate_gaps:Array<{requirement_id:number;title:string;category:string;priority:string;responsible_function:string|null;source_document:string|null;source_page:string|null;source_clause:string|null;reason:string}>;open_gaps_by_function:Array<{name:string;count:number}>;open_gaps_by_category:Array<{name:string;count:number}>;action_plan:Array<{source_kind:string;source_id:number;missing_input_id:number|null;requirement_id:number|null;title:string;priority:string;responsible_function:string|null;due_date:string|null;is_overdue:boolean;reason:string;recommended_action:string}>;closure_summary:{unreviewed_requirements:number;unassessed_compliance:number;requirements_needing_clarification:number;requirements_with_open_gaps:number};methodology:{information_completeness_weight:number;review_completion_weight:number;compliance_assessment_weight:number;blocker_control_weight:number;version:string}};
export type PreBidQuery={id:number;bid_project_id:number;requirement_id:number|null;missing_input_id:number|null;source_document_id:number|null;query_number:string|null;query_title:string;query_text:string;query_category:string;responsible_function:string|null;responsible_person:string|null;priority:string;status:string;target_response_date:string|null;submitted_date:string|null;employer_response:string|null;response_date:string|null;response_reference:string|null;impact_if_unresolved:string|null;source_page:string|null;source_clause:string|null;source_section:string|null;source_excerpt:string|null;created_by:number;created_at:string;updated_at:string;approved_by:number|null;approved_at:string|null;closed_by:number|null;closed_at:string|null;requirement_title:string|null;missing_input_title:string|null;source_original_filename:string|null;source_document_title:string|null};
export type PreBidQueryPage=Page<PreBidQuery>&{summary:{total:number;draft:number;submitted:number;responded:number;open:number;overdue:number}};

export type TenderKnowledgeCheck={status:"unresolved"|"related_evidence_found"|"answered_in_tender";confidence:number;evidence_count:number;answer_excerpt:string|null;source_document:string|null;source_page:string|null;source_clause:string|null};
export type PreBidQuerySuggestion={source_kind:string;source_id:number;rationale:string;confidence:number;knowledge_check:TenderKnowledgeCheck;query:{query_title:string;query_text:string;query_category:string;priority:string;responsible_function:string|null;requirement_id:number|null;missing_input_id:number|null;source_document_id:number|null;source_page:string|null;source_clause:string|null;source_section:string|null;source_excerpt:string|null;impact_if_unresolved:string|null;status:"Draft"}};
export type TenderAnsweredIssue={source_kind:string;source_id:number;title:string;knowledge_check:TenderKnowledgeCheck};
export type SuppressedPreBidQuerySuggestion={source_kind:string;source_id:number;decision:string;reason:string|null;decided_at:string};
export type PreBidQuerySuggestionResponse={provider:string;knowledge_provider:string;items:PreBidQuerySuggestion[];answered:TenderAnsweredIssue[];suppressed:SuppressedPreBidQuerySuggestion[];summary:{suggested:number;answered_in_tender:number;automatic_discoveries:number;suppressed:number}};
