"use client";
import Link from "next/link";import {use,useCallback,useEffect,useState} from "react";
import {Card} from "@/components/ui";
import {BidWorkspaceHeader} from "@/components/BidWorkspaceHeader";
import {ConfidenceBadge,DataTableShell,Drawer,EmptyState,ErrorState,FilterBar,KeyValueGrid,LoadingState,PageHeader,PrimaryButton,SectionHeader,SecondaryButton,SearchInput,StatusBadge,SummaryCard} from "@/components/design-system";
import {UploadOutcome,UploadZone} from "@/features/documents/UploadZone";
import {API,request} from "@/services/api";
import type {Bid,Document,Page} from "@/types";

const categories=["Notice / Invitation","Instructions to Bidders","Bid Data Sheet","Conditions of Contract","Employer's Requirements","Technical Specifications","BOQ / Price Schedule","Drawings","Forms / Formats / Schedules","Qualification Requirements","Evaluation Criteria","Scope of Work","Addendum / Corrigendum","Pre-Bid Clarification","Reference Document","Other"];
const empty:UploadOutcome={total:0,stored:0,duplicates:0,unsupported:0,failed:0,requiringClassification:0};

export default function BidDocuments({params}:{params:Promise<{id:string}>}){
 const {id}=use(params),[outcome,setOutcome]=useState(empty),[refresh,setRefresh]=useState(0),[bid,setBid]=useState<Bid|null>(null);useEffect(()=>{request<Bid>(`/bids/${id}`).then(setBid).catch(()=>{})},[id]);
 return <div className="mx-auto max-w-[1500px]"><BidWorkspaceHeader bid={bid} active="Documents"/><PageHeader items={[{label:"Bid Workspace",href:"/bids"},{label:"Documents"}]} title="Tender Document Repository" description="Upload tender documents once. The system reads their content, classifies them automatically and extracts bid requirements." action={<PrimaryButton onClick={()=>document.getElementById("document-upload")?.scrollIntoView({behavior:"smooth"})}>Upload Documents</PrimaryButton>}/>
  <Card className="p-4" id="document-upload"><SectionHeader>Automatic Document Intake</SectionHeader><UploadZone bidId={Number(id)} onComplete={x=>{setOutcome(x);setRefresh(n=>n+1)}}/></Card>
  {outcome.total+outcome.unsupported>0&&<div className="my-3 grid gap-2 md:grid-cols-6">{[["Files Selected",outcome.total+outcome.unsupported],["Stored",outcome.stored],["Require Classification",outcome.requiringClassification],["Duplicates",outcome.duplicates],["Unsupported",outcome.unsupported],["Failed",outcome.failed]].map(([a,b])=><Card className="p-3" key={a}><div className="text-2xl font-bold text-navy">{b}</div><div className="text-xs text-slate-500">{a}</div></Card>)}</div>}
  <Repository bidId={Number(id)} refresh={refresh}/>
 </div>
}

function Repository({bidId,refresh}:{bidId:number;refresh:number}){
 const [data,setData]=useState<Page<Document>>({items:[],total:0,page:1,page_size:20}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[filters,setFilters]=useState({search:"",category:"",extension:"",status:"",uploader:"",uploaded_date:""}),[page,setPage]=useState(1),[selected,setSelected]=useState<Document|null>(null),[remarking,setRemarking]=useState<Document|null>(null);
 const load=useCallback(()=>{setLoading(true);const q=new URLSearchParams({page:String(page),page_size:"20"});Object.entries(filters).forEach(([k,v])=>v&&q.set(k,v));request<Page<Document>>(`/bids/${bidId}/documents?${q}`).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[bidId,page,filters,refresh]);
 useEffect(load,[load]);
 const mutate=async(path:string,init:RequestInit)=>{await request(path,init);setSelected(null);setRemarking(null);load()};
 const activeFilters=Object.values(filters).filter(Boolean).length,classified=data.items.filter(d=>d.classification_status==="classified"||d.classification_status==="manually_classified").length,needsReview=data.items.filter(d=>d.classification_status==="needs_review").length;
 return <div className="mt-3 space-y-2.5"><div className="grid grid-cols-2 gap-2 md:grid-cols-4"><SummaryCard label="Total Documents" value={data.total}/><SummaryCard label="Classified on page" value={classified} tone="green"/><SummaryCard label="Needs Review on page" value={needsReview} tone="amber"/><SummaryCard label="Latest on page" value={data.items.filter(d=>d.is_latest_version).length}/></div><DataTableShell><div className="flex items-center justify-between border-b px-4 py-2.5"><div><h2 className="font-bold text-slate-900">Documents</h2><p className="text-xs text-slate-500">Controlled tender files and classification status</p></div></div><FilterBar activeCount={activeFilters} onClear={()=>setFilters({search:"",category:"",extension:"",status:"",uploader:"",uploaded_date:""})}>
  <SearchInput aria-label="Search filename" placeholder="Search documents" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/>
  <select aria-label="All categories" className="rounded border p-2 text-sm" value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}><option value="">All categories</option>{categories.map(v=><option key={v}>{v}</option>)}</select>
  {[ ["extension","All extensions",["pdf","docx","xlsx","csv","zip","xml"]], ["status","All statuses",["Needs Review","Uploaded","Duplicate","Archived"]] ].map(([key,label,values]:any)=><select key={key} aria-label={label} className="rounded border p-2 text-sm" value={(filters as any)[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})}><option value="">{label}</option>{values.map((v:string)=><option key={v}>{v}</option>)}</select>)}
  <input aria-label="Uploader ID" placeholder="Uploader ID" className="rounded border p-2 text-sm" value={filters.uploader} onChange={e=>setFilters({...filters,uploader:e.target.value})}/><input aria-label="Upload date" type="date" className="rounded border p-2 text-sm" value={filters.uploaded_date} onChange={e=>setFilters({...filters,uploaded_date:e.target.value})}/>
 </FilterBar>
 {error?<ErrorState/>:loading?<LoadingState label="Loading tender documents…"/>:data.items.length===0?<EmptyState title={activeFilters?"No documents match these filters":"No tender documents uploaded yet"} description={activeFilters?"Clear filters or adjust your search.":"Upload tender documents and the system will classify them and extract requirements automatically."}/>:<><div className="space-y-2 p-3 md:hidden">{data.items.map(d=><article key={d.id} className="rounded border border-slate-200 bg-white p-3 shadow-sm">
 <div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="truncate text-sm font-semibold text-slate-900">{d.document_title||d.original_filename}</div>{d.document_title&&<div className="mt-0.5 truncate text-[11px] text-slate-500">{d.original_filename}</div>}</div><StatusBadge tone={d.classification_status==="manually_classified"||d.classification_status==="classified"?"green":d.classification_status==="needs_review"?"amber":"grey"}>{classificationLabel(d.classification_status)}</StatusBadge></div>
 <div className="mt-3 grid grid-cols-2 gap-x-3 gap-y-2 text-xs"><div><span className="text-slate-500">Category</span><div className="mt-0.5 font-medium text-slate-800">{d.document_category||"Unclassified"}</div></div><div><span className="text-slate-500">Type</span><div className="mt-0.5 font-medium text-slate-800">{d.document_type||"—"}</div></div><div><span className="text-slate-500">Confidence</span><div className="mt-0.5"><ConfidenceBadge value={d.classification_status==="manually_classified"?null:d.classification_confidence}/></div></div><div><span className="text-slate-500">Revision</span><div className="mt-0.5 font-medium text-slate-800">{d.revision||"—"}</div></div></div>
 <div className="mt-3 flex flex-wrap gap-2 border-t pt-3 text-xs"><button onClick={()=>setSelected(d)} className="rounded border border-slate-300 px-3 py-2 font-semibold text-blue-700">View</button><a className="rounded border border-slate-300 px-3 py-2 font-semibold text-blue-700" href={`${API}/documents/${d.id}/download`}>Download</a><button onClick={()=>setRemarking(d)} className="rounded bg-[#e2b635] px-3 py-2 font-semibold text-[#243241]">{d.notes?"Edit Remark":"Add Remark"}</button></div>
 </article>)}</div><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wide text-slate-500"><tr>{["Document","Category","Type","Revision","Classification","Confidence","Uploaded","Actions"].map(x=><th className="px-4 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{data.items.map(d=><tr className="border-t" key={d.id}>
  <td className="px-4 py-3"><div className="font-semibold">{d.document_title||d.original_filename}</div>{d.document_title&&<div className="text-xs text-slate-500">{d.original_filename}</div>}</td>
  <td className="px-4">{d.document_category||"Unclassified"}</td><td className="px-4">{d.document_type||"—"}</td><td className="px-4">{d.revision||"—"}</td>
  <td className="px-4"><StatusBadge tone={d.classification_status==="manually_classified"||d.classification_status==="classified"?"green":d.classification_status==="needs_review"?"amber":"grey"}>{classificationLabel(d.classification_status)}</StatusBadge></td><td className="px-4"><ConfidenceBadge value={d.classification_status==="manually_classified"?null:d.classification_confidence}/></td><td className="px-4 whitespace-nowrap text-xs text-slate-600">{new Date(d.uploaded_at).toLocaleString()}</td>
  <td className="px-4"><div className="flex flex-wrap gap-x-2 gap-y-1 whitespace-nowrap text-xs sm:text-sm"><button onClick={()=>setSelected(d)} className="font-semibold text-blue-700">View</button><span className="text-slate-300">·</span><a className="font-semibold text-blue-700" href={`${API}/documents/${d.id}/download`}>Download</a><span className="text-slate-300">·</span><button onClick={()=>setRemarking(d)} className="font-semibold text-blue-700">{d.notes?"Edit Remark":"Add Remark"}</button></div></td>
 </tr>)}</tbody></table></div></>}
 <div className="flex items-center justify-between border-t p-4 text-sm"><span>{data.total} documents</span><div><button disabled={page===1} onClick={()=>setPage(p=>p-1)} className="mr-2 rounded border px-3 py-1 disabled:opacity-40">Previous</button><span>Page {page}</span><button disabled={page*20>=data.total} onClick={()=>setPage(p=>p+1)} className="ml-2 rounded border px-3 py-1 disabled:opacity-40">Next</button></div></div>
 {selected&&<DocumentDetail doc={selected} close={()=>setSelected(null)}/>} {remarking&&<RemarkDrawer doc={remarking} close={()=>setRemarking(null)} save={notes=>mutate(`/documents/${remarking.id}/notes`,{method:"PATCH",body:JSON.stringify({notes})})}/>}</DataTableShell></div>
}
function classificationLabel(status:Document["classification_status"]){return !status||status==="pending"?"Pending Classification":status==="manually_classified"?"Manually Classified":status==="needs_review"?"Needs Review":"Auto Classified"}
function DocumentDetail({doc,close}:{doc:Document;close:()=>void}){return <Drawer title={doc.document_title||doc.original_filename} subtitle="Document metadata" close={close}><div className="space-y-6"><section><SectionHeader>Document Information</SectionHeader><KeyValueGrid items={[{label:"Original filename",value:doc.original_filename},{label:"Category",value:doc.document_category||"Unclassified"},{label:"Document type",value:doc.document_type},{label:"Document number",value:doc.document_number}]}/></section><section><SectionHeader>Classification</SectionHeader><KeyValueGrid items={[{label:"Status",value:classificationLabel(doc.classification_status)},{label:"Confidence",value:doc.classification_confidence===null?"—":`${Math.round(doc.classification_confidence*100)}%`},{label:"Document status",value:doc.document_status}]}/></section><section><SectionHeader>Revision &amp; Upload</SectionHeader><KeyValueGrid items={[{label:"Revision",value:doc.revision},{label:"Latest version",value:doc.is_latest_version?"Yes":"No"},{label:"Uploaded",value:new Date(doc.uploaded_at).toLocaleString()},{label:"File type",value:doc.file_extension.toUpperCase()}]}/></section>{doc.notes&&<section><SectionHeader>User Remark</SectionHeader><p className="text-sm text-slate-700">{doc.notes}</p></section>}</div></Drawer>}
function RemarkDrawer({doc,close,save}:{doc:Document;close:()=>void;save:(notes:string|null)=>void}){
 const [notes,setNotes]=useState(doc.notes||"");
 return <Drawer title="Document Remark" subtitle={doc.document_title||doc.original_filename} close={close} footer={<div className="flex justify-end gap-2"><SecondaryButton onClick={close}>Cancel</SecondaryButton><PrimaryButton onClick={()=>save(notes.trim()||null)}>Save Remark</PrimaryButton></div>}><div className="space-y-3"><p className="text-sm text-slate-600">Add a user remark only. Document classification and requirement extraction are handled automatically by the system.</p><div className="field"><label>Remark</label><textarea rows={6} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Add a note, observation or follow-up for this document."/></div></div></Drawer>
}
