"use client";
import Link from "next/link";import {use,useCallback,useEffect,useState} from "react";
import {Card} from "@/components/ui";
import {BidWorkspaceHeader} from "@/components/BidWorkspaceHeader";
import {ConfidenceBadge,DataTableShell,Drawer,EmptyState,ErrorState,FilterBar,KeyValueGrid,LoadingState,PageHeader,PrimaryButton,SectionHeader,SecondaryButton,SearchInput,StatusBadge,SummaryCard} from "@/components/design-system";
import {UploadOutcome,UploadZone} from "@/features/documents/UploadZone";
import {API,request} from "@/services/api";
import type {Bid,Document,Page,RequirementExtractionSummary} from "@/types";

const categories=["Notice / Invitation","Instructions to Bidders","Bid Data Sheet","Conditions of Contract","Employer's Requirements","Technical Specifications","BOQ / Price Schedule","Drawings","Forms / Formats / Schedules","Qualification Requirements","Evaluation Criteria","Scope of Work","Addendum / Corrigendum","Pre-Bid Clarification","Reference Document","Other"];
const empty:UploadOutcome={total:0,stored:0,duplicates:0,unsupported:0,failed:0,requiringClassification:0};

export default function BidDocuments({params}:{params:Promise<{id:string}>}){
 const {id}=use(params),[outcome,setOutcome]=useState(empty),[refresh,setRefresh]=useState(0),[bid,setBid]=useState<Bid|null>(null);useEffect(()=>{request<Bid>(`/bids/${id}`).then(setBid).catch(()=>{})},[id]);
 return <div className="mx-auto max-w-[1500px]"><BidWorkspaceHeader bid={bid} active="Documents"/><PageHeader items={[{label:"Bid Workspace",href:"/bids"},{label:"Documents"}]} title="Tender Document Repository" description="Upload, classify, review and extract requirements from tender documents." action={<PrimaryButton onClick={()=>document.getElementById("document-upload")?.scrollIntoView({behavior:"smooth"})}>Upload Documents</PrimaryButton>}/>
  <Card className="p-4" id="document-upload"><SectionHeader>Bulk Document Upload</SectionHeader><UploadZone bidId={Number(id)} onComplete={x=>{setOutcome(x);setRefresh(n=>n+1)}}/></Card>
  {outcome.total+outcome.unsupported>0&&<div className="my-3 grid gap-2 md:grid-cols-6">{[["Files Selected",outcome.total+outcome.unsupported],["Stored",outcome.stored],["Require Classification",outcome.requiringClassification],["Duplicates",outcome.duplicates],["Unsupported",outcome.unsupported],["Failed",outcome.failed]].map(([a,b])=><Card className="p-3" key={a}><div className="text-2xl font-bold text-navy">{b}</div><div className="text-xs text-slate-500">{a}</div></Card>)}</div>}
  <Repository bidId={Number(id)} refresh={refresh}/>
 </div>
}

function Repository({bidId,refresh}:{bidId:number;refresh:number}){
 const [data,setData]=useState<Page<Document>>({items:[],total:0,page:1,page_size:20}),[loading,setLoading]=useState(true),[error,setError]=useState(""),[filters,setFilters]=useState({search:"",category:"",extension:"",status:"",uploader:"",uploaded_date:""}),[page,setPage]=useState(1),[selected,setSelected]=useState<Document|null>(null),[editing,setEditing]=useState<Document|null>(null),[extraction,setExtraction]=useState<RequirementExtractionSummary|null>(null),[extracting,setExtracting]=useState<number|null>(null);
 const load=useCallback(()=>{setLoading(true);const q=new URLSearchParams({page:String(page),page_size:"20"});Object.entries(filters).forEach(([k,v])=>v&&q.set(k,v));request<Page<Document>>(`/bids/${bidId}/documents?${q}`).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[bidId,page,filters,refresh]);
 useEffect(load,[load]);
 const mutate=async(path:string,init:RequestInit)=>{await request(path,init);setSelected(null);setEditing(null);load()};
 const extract=async(doc:Document)=>{setExtracting(doc.id);setError("");try{setExtraction(await request<RequirementExtractionSummary>(`/documents/${doc.id}/extract-requirements`,{method:"POST"}))}catch(e){setError(e instanceof Error?e.message:"Requirement extraction failed")}finally{setExtracting(null)}};
 const activeFilters=Object.values(filters).filter(Boolean).length,classified=data.items.filter(d=>d.classification_status==="classified"||d.classification_status==="manually_classified").length,needsReview=data.items.filter(d=>d.classification_status==="needs_review").length;
 return <div className="mt-3 space-y-2.5"><div className="grid grid-cols-2 gap-2 md:grid-cols-4"><SummaryCard label="Total Documents" value={data.total}/><SummaryCard label="Classified on page" value={classified} tone="green"/><SummaryCard label="Needs Review on page" value={needsReview} tone="amber"/><SummaryCard label="Latest on page" value={data.items.filter(d=>d.is_latest_version).length}/></div><DataTableShell><div className="flex items-center justify-between border-b px-4 py-2.5"><div><h2 className="font-bold text-slate-900">Documents</h2><p className="text-xs text-slate-500">Controlled tender files and classification status</p></div></div><FilterBar activeCount={activeFilters} onClear={()=>setFilters({search:"",category:"",extension:"",status:"",uploader:"",uploaded_date:""})}>
  <SearchInput aria-label="Search filename" placeholder="Search documents" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/>
  <select aria-label="All categories" className="rounded border p-2 text-sm" value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}><option value="">All categories</option>{categories.map(v=><option key={v}>{v}</option>)}</select>
  {[ ["extension","All extensions",["pdf","docx","xlsx","csv","zip","xml"]], ["status","All statuses",["Needs Review","Uploaded","Duplicate","Archived"]] ].map(([key,label,values]:any)=><select key={key} aria-label={label} className="rounded border p-2 text-sm" value={(filters as any)[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})}><option value="">{label}</option>{values.map((v:string)=><option key={v}>{v}</option>)}</select>)}
  <input aria-label="Uploader ID" placeholder="Uploader ID" className="rounded border p-2 text-sm" value={filters.uploader} onChange={e=>setFilters({...filters,uploader:e.target.value})}/><input aria-label="Upload date" type="date" className="rounded border p-2 text-sm" value={filters.uploaded_date} onChange={e=>setFilters({...filters,uploaded_date:e.target.value})}/>
 </FilterBar>
 {error?<ErrorState/>:loading?<LoadingState label="Loading tender documents…"/>:data.items.length===0?<EmptyState title={activeFilters?"No documents match these filters":"No tender documents uploaded yet"} description={activeFilters?"Clear filters or adjust your search.":"Upload tender documents to begin classification and requirement extraction."}/>:<div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-slate-50 text-[11px] uppercase tracking-wide text-slate-500"><tr>{["Document","Category","Type","Revision","Classification","Confidence","Uploaded","Actions"].map(x=><th className="px-4 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{data.items.map(d=><tr className="border-t" key={d.id}>
  <td className="px-4 py-3"><div className="font-semibold">{d.document_title||d.original_filename}</div>{d.document_title&&<div className="text-xs text-slate-500">{d.original_filename}</div>}</td>
  <td className="px-4">{d.document_category||"Unclassified"}</td><td className="px-4">{d.document_type||"—"}</td><td className="px-4">{d.revision||"—"}</td>
  <td className="px-4"><StatusBadge tone={d.classification_status==="manually_classified"||d.classification_status==="classified"?"green":d.classification_status==="needs_review"?"amber":"grey"}>{classificationLabel(d.classification_status)}</StatusBadge></td><td className="px-4"><ConfidenceBadge value={d.classification_status==="manually_classified"?null:d.classification_confidence}/></td><td className="px-4 whitespace-nowrap text-xs text-slate-600">{new Date(d.uploaded_at).toLocaleString()}</td>
  <td className="px-4"><div className="whitespace-nowrap"><button onClick={()=>setSelected(d)} className="font-semibold text-blue-700">View</button> · <a className="font-semibold text-blue-700" href={`${API}/documents/${d.id}/download`}>Download</a> · <button onClick={()=>setEditing(d)} className="font-semibold text-blue-700">{d.classification_status==="needs_review"?"Review Classification":"Edit Metadata"}</button></div><div className="mt-1 flex gap-3 text-xs font-semibold text-slate-600"><button onClick={()=>rerun(d,mutate)}>Re-run Classification</button>{!d.duplicate_of_document_id&&d.document_status!=="Archived"&&<button disabled={extracting===d.id} onClick={()=>extract(d)} className="text-blue-700 disabled:opacity-50">{extracting===d.id?"Extracting…":"Extract Requirements"}</button>}</div></td>
 </tr>)}</tbody></table></div>}
 <div className="flex items-center justify-between border-t p-4 text-sm"><span>{data.total} documents</span><div><button disabled={page===1} onClick={()=>setPage(p=>p-1)} className="mr-2 rounded border px-3 py-1 disabled:opacity-40">Previous</button><span>Page {page}</span><button disabled={page*20>=data.total} onClick={()=>setPage(p=>p+1)} className="ml-2 rounded border px-3 py-1 disabled:opacity-40">Next</button></div></div>
 {selected&&<DocumentDetail doc={selected} close={()=>setSelected(null)}/>} {extraction&&<Drawer title="Requirement Extraction Complete" subtitle={extraction.extractor_version} close={()=>setExtraction(null)}><div className="space-y-3 text-sm"><p className="text-xl font-bold text-slate-900">{extraction.created} requirements extracted</p><KeyValueGrid items={[{label:"Duplicates skipped",value:extraction.skipped_duplicates},{label:"Low-confidence skipped",value:extraction.low_confidence_skipped}]}/>{extraction.no_text&&<p className="rounded bg-amber-50 p-3 text-amber-800">No extractable text was found. No requirements were created.</p>}<Link href={`/bids/${bidId}/requirements`} className="inline-block rounded bg-blue-700 px-4 py-2 font-semibold text-white">View Requirement Register</Link></div></Drawer>}
 {editing&&<MetadataModal doc={editing} close={()=>setEditing(null)} save={payload=>mutate(`/documents/${editing.id}/metadata`,{method:"PATCH",body:JSON.stringify(payload)})}/>}</DataTableShell></div>
}
function classificationLabel(status:Document["classification_status"]){return !status||status==="pending"?"Pending Classification":status==="manually_classified"?"Manually Classified":status==="needs_review"?"Needs Review":"Auto Classified"}
function rerun(doc:Document,mutate:(path:string,init:RequestInit)=>Promise<void>){const force=doc.classification_status==="manually_classified";if(force&&!confirm("This document was manually classified. Replace the human classification with an automatic result?"))return;mutate(`/documents/${doc.id}/auto-classify`,{method:"POST",body:JSON.stringify({force})})}
function DocumentDetail({doc,close}:{doc:Document;close:()=>void}){return <Drawer title={doc.document_title||doc.original_filename} subtitle="Document metadata" close={close}><div className="space-y-6"><section><SectionHeader>Document Information</SectionHeader><KeyValueGrid items={[{label:"Original filename",value:doc.original_filename},{label:"Category",value:doc.document_category||"Unclassified"},{label:"Document type",value:doc.document_type},{label:"Document number",value:doc.document_number}]}/></section><section><SectionHeader>Classification</SectionHeader><KeyValueGrid items={[{label:"Status",value:classificationLabel(doc.classification_status)},{label:"Confidence",value:doc.classification_confidence===null?"—":`${Math.round(doc.classification_confidence*100)}%`},{label:"Document status",value:doc.document_status}]}/></section><section><SectionHeader>Revision &amp; Upload</SectionHeader><KeyValueGrid items={[{label:"Revision",value:doc.revision},{label:"Latest version",value:doc.is_latest_version?"Yes":"No"},{label:"Uploaded",value:new Date(doc.uploaded_at).toLocaleString()},{label:"File type",value:doc.file_extension.toUpperCase()}]}/></section>{doc.remarks&&<section><SectionHeader>Remarks</SectionHeader><p className="text-sm text-slate-700">{doc.remarks}</p></section>}</div></Drawer>}
function MetadataModal({doc,close,save}:{doc:Document;close:()=>void;save:(x:unknown)=>void}){
 const [form,setForm]=useState({document_category:doc.document_category||"",document_type:doc.document_type||"",document_number:doc.document_number||"",document_title:doc.document_title||"",revision:doc.revision||"",document_date:doc.document_date||"",remarks:doc.remarks||""});
 const field=(key:keyof typeof form,label:string,type="text")=><div className="field"><label>{label}</label><input type={type} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></div>;
 return <Drawer title="Edit Document Metadata" subtitle={doc.original_filename} close={close} footer={<div className="flex justify-end gap-2"><SecondaryButton onClick={close}>Cancel</SecondaryButton><PrimaryButton onClick={()=>save(Object.fromEntries(Object.entries(form).map(([k,v])=>[k,v||null])))}>Save Metadata</PrimaryButton></div>}><div className="space-y-6"><section><SectionHeader>Document Information</SectionHeader><div className="grid gap-4 md:grid-cols-2"><div className="field md:col-span-2"><label>Category</label><select value={form.document_category} onChange={e=>setForm({...form,document_category:e.target.value})}><option value="">Unclassified</option>{categories.map(x=><option key={x}>{x}</option>)}</select></div>{field("document_type","Document Type")}{field("document_number","Document Number")}{field("document_title","Document Title")}</div></section><section><SectionHeader>Revision</SectionHeader><div className="grid gap-4 md:grid-cols-2">{field("revision","Revision")}{field("document_date","Document Date","date")}</div></section><section><SectionHeader>Remarks</SectionHeader><div className="field"><label>Remarks</label><textarea rows={4} value={form.remarks} onChange={e=>setForm({...form,remarks:e.target.value})}/></div></section></div></Drawer>
}
