"use client";
import Link from "next/link";
import {ChevronRight,LoaderCircle,Search,X} from "lucide-react";

const focus="focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-600 focus-visible:ring-offset-2";
export function PrimaryButton({children,className="",...props}:React.ButtonHTMLAttributes<HTMLButtonElement>){return <button {...props} className={`rounded-md bg-blue-700 px-3.5 py-2 text-sm font-semibold text-white hover:bg-blue-800 disabled:cursor-not-allowed disabled:opacity-50 ${focus} ${className}`}>{children}</button>}
export function SecondaryButton({children,className="",...props}:React.ButtonHTMLAttributes<HTMLButtonElement>){return <button {...props} className={`rounded-md border border-slate-300 bg-white px-3.5 py-2 text-sm font-semibold text-slate-700 hover:border-blue-300 hover:bg-blue-50 ${focus} ${className}`}>{children}</button>}
export function GhostButton({children,className="",...props}:React.ButtonHTMLAttributes<HTMLButtonElement>){return <button {...props} className={`rounded px-2.5 py-1.5 text-sm font-semibold text-blue-700 hover:bg-blue-50 ${focus} ${className}`}>{children}</button>}
export function Breadcrumbs({items}:{items:{label:string;href?:string}[]}){return <nav aria-label="Breadcrumb" className="mb-2 flex items-center gap-1 text-xs font-medium text-slate-500">{items.map((item,index)=><span className="flex items-center gap-1" key={item.label}>{index>0&&<ChevronRight size={12}/>} {item.href?<Link className="hover:text-blue-700" href={item.href}>{item.label}</Link>:<span>{item.label}</span>}</span>)}</nav>}
export function PageHeader({title,description,items,action}:{title:string;description:string;items:{label:string;href?:string}[];action?:React.ReactNode}){return <header className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><Breadcrumbs items={items}/><h1 className="text-2xl font-bold tracking-tight text-slate-900">{title}</h1><p className="mt-1 max-w-2xl text-sm text-slate-500">{description}</p></div>{action}</header>}
export function SummaryCard({label,value,tone="blue"}:{label:string;value:React.ReactNode;tone?:"blue"|"green"|"amber"|"red"}){const dot={blue:"bg-blue-600",green:"bg-emerald-600",amber:"bg-amber-500",red:"bg-red-600"}[tone];return <div className="rounded-md border border-slate-200 bg-white px-4 py-3 shadow-[0_1px_2px_rgba(15,23,42,.04)]"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-wide text-slate-500"><span className={`h-2 w-2 rounded-full ${dot}`}/>{label}</div><div className="mt-1 text-2xl font-bold text-slate-900">{value}</div></div>}
type Tone="blue"|"green"|"amber"|"red"|"grey";
export function StatusBadge({children,tone="grey"}:{children:React.ReactNode;tone?:Tone}){const styles={blue:"border-blue-200 bg-blue-50 text-blue-700",green:"border-emerald-200 bg-emerald-50 text-emerald-700",amber:"border-amber-200 bg-amber-50 text-amber-800",red:"border-red-200 bg-red-50 text-red-700",grey:"border-slate-200 bg-slate-50 text-slate-600"}[tone];return <span className={`inline-flex whitespace-nowrap rounded-full border px-2 py-0.5 text-[11px] font-semibold ${styles}`}>{children}</span>}
export function PriorityBadge({value}:{value:string}){return <StatusBadge tone={value==="Critical"?"red":value==="High"?"amber":value==="Medium"?"blue":"grey"}>{value}</StatusBadge>}
export function ConfidenceBadge({value}:{value:number|null}){if(value===null)return <span className="text-slate-400">—</span>;return <StatusBadge tone={value>=.8?"green":value>=.6?"amber":"red"}>{Math.round(value*100)}%</StatusBadge>}
export function FilterBar({children,onClear,activeCount=0}:{children:React.ReactNode;onClear:()=>void;activeCount?:number}){return <div className="flex flex-wrap items-center gap-2 border-b border-slate-200 bg-slate-50/70 p-3">{children}<button onClick={onClear} className={`ml-auto rounded px-2.5 py-2 text-xs font-semibold ${activeCount?"text-blue-700 hover:bg-blue-50":"text-slate-400"}`}>Clear filters{activeCount?` (${activeCount})`:""}</button></div>}
export function SearchInput(props:React.InputHTMLAttributes<HTMLInputElement>){return <label className="relative min-w-52 flex-1"><span className="sr-only">Search</span><Search className="absolute left-2.5 top-2.5 text-slate-400" size={15}/><input {...props} className="w-full rounded-md border border-slate-300 bg-white py-2 pl-8 pr-3 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100"/></label>}
export function DataTableShell({children}:{children:React.ReactNode}){return <section className="overflow-hidden rounded-md border border-slate-200 bg-white shadow-[0_1px_2px_rgba(15,23,42,.04)]">{children}</section>}
export function LoadingState({label="Loading…"}:{label?:string}){return <div className="flex items-center justify-center gap-2 p-12 text-sm text-slate-500"><LoaderCircle className="animate-spin" size={18}/>{label}</div>}
export function ErrorState({message="We could not load this information. Please try again."}:{message?:string}){return <div role="alert" className="m-4 rounded-md border border-red-200 bg-red-50 p-4 text-sm text-red-700">{message}</div>}
export function EmptyState({title,description,action}:{title:string;description:string;action?:React.ReactNode}){return <div className="px-6 py-14 text-center"><div className="font-semibold text-slate-800">{title}</div><p className="mx-auto mt-1 max-w-md text-sm text-slate-500">{description}</p>{action&&<div className="mt-4">{action}</div>}</div>}
export function Drawer({title,subtitle,close,children,footer}:{title:string;subtitle?:string;close:()=>void;children:React.ReactNode;footer?:React.ReactNode}){return <div className="fixed inset-0 z-50 bg-slate-950/35" role="dialog" aria-modal="true" aria-label={title} onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><aside className="ml-auto flex h-full w-full max-w-2xl flex-col bg-white shadow-2xl"><header className="flex items-start justify-between border-b px-5 py-4"><div><h2 className="font-bold text-slate-900">{title}</h2>{subtitle&&<p className="mt-0.5 text-xs text-slate-500">{subtitle}</p>}</div><button aria-label="Close drawer" className={`rounded p-1.5 text-slate-500 hover:bg-slate-100 ${focus}`} onClick={close}><X size={18}/></button></header><div className="flex-1 overflow-y-auto p-5">{children}</div>{footer&&<footer className="border-t bg-white px-5 py-3">{footer}</footer>}</aside></div>}
export function SectionHeader({children}:{children:React.ReactNode}){return <h3 className="mb-3 border-b border-slate-200 pb-2 text-xs font-bold uppercase tracking-wider text-blue-800">{children}</h3>}
export function KeyValueGrid({items}:{items:{label:string;value:React.ReactNode}[]}){return <dl className="grid gap-x-5 gap-y-4 sm:grid-cols-2">{items.map(x=><div key={x.label}><dt className="text-[11px] font-semibold uppercase tracking-wide text-slate-500">{x.label}</dt><dd className="mt-1 text-sm text-slate-800">{x.value||"—"}</dd></div>)}</dl>}
export function SourceEvidenceCard({document,page,clause,section,excerpt}:{document:string;page?:string|null;clause?:string|null;section?:string|null;excerpt?:string|null}){return <div className="rounded-md border border-blue-100 bg-blue-50/50 p-4"><div className="font-semibold text-slate-900">{document}</div><div className="mt-1 text-xs text-slate-500">{[page&&`Page ${page}`,clause&&`Clause ${clause}`,section].filter(Boolean).join(" · ")||"No page or clause reference"}</div>{excerpt&&<blockquote className="mt-3 border-l-2 border-blue-500 pl-3 text-sm leading-6 text-slate-700">{excerpt}</blockquote>}</div>}
