"use client";

import Link from "next/link";
import {usePathname} from "next/navigation";
import {FileQuestion,FileSearch,Files,FolderKanban,LayoutDashboard,LockKeyhole,PlusSquare,Settings,ShieldCheck,TriangleAlert} from "lucide-react";

const management=[{n:"Dashboard",h:"/",i:LayoutDashboard},{n:"My Bids",h:"/bids",i:FolderKanban},{n:"Create New Bid",h:"/bids/new",i:PlusSquare}];
const future=["Reviews","Submission"];

export function Sidebar(){const p=usePathname();const bidMatch=p.match(/^\/bids\/([^/]+)(?:\/|$)/);const bidId=bidMatch?.[1];const workspace=[{n:"Documents",h:bidId?`/bids/${bidId}/documents`:undefined,i:Files},{n:"Requirement Register",h:bidId?`/bids/${bidId}/requirements`:undefined,i:FileSearch},{n:"Missing Inputs",h:bidId?`/bids/${bidId}/missing-inputs`:undefined,i:TriangleAlert},{n:"Pre-Bid Queries",h:bidId?`/bids/${bidId}/pre-bid-queries`:undefined,i:FileQuestion}];const item=(x:any)=>{const selected=x.h?(x.h==="/"?p===x.h:p===x.h||p.startsWith(x.h+"/")):false;if(x.h)return <Link key={x.n} href={x.h} className={`mb-1 flex items-center gap-3 rounded-md px-3 py-2 text-sm ${selected?"bg-blue-600 font-semibold text-white":"text-slate-300 hover:bg-white/5 hover:text-white"}`}><x.i size={16}/>{x.n}</Link>;return <div key={x.n} aria-disabled="true" className="mb-1 flex items-center gap-3 rounded-md px-3 py-2 text-sm text-slate-500"><x.i size={16}/>{x.n}</div>};return <aside className="fixed hidden h-screen w-60 flex-col bg-[#082744] text-white md:flex"><div className="border-b border-white/10 px-5 py-5"><div className="text-base font-bold">Railway Bid Intelligence</div><div className="mt-1 text-[10px] font-semibold uppercase tracking-[.18em] text-blue-200">L&amp;T Bid Workspace</div></div><nav className="flex-1 overflow-y-auto px-3 py-4"><div className="nav-label">Bid Management</div>{management.map(item)}<div className="nav-label mt-5">Bid Workspace</div>{workspace.map(item)}{future.map(n=><div key={n} className="flex items-center justify-between px-3 py-2 text-xs text-slate-500"><span>{n}</span><LockKeyhole size={11}/></div>)}<div className="nav-label mt-5">Governance</div>{item({n:"Audit Log",h:"/audit",i:ShieldCheck})}</nav><Link href="/settings" className="m-3 flex gap-3 border-t border-white/10 p-3 text-sm text-slate-300 hover:text-white"><Settings size={16}/>Settings</Link></aside>}
