"""Explicit Phase 1 schema.

Revision ID: 0001
"""
from alembic import op
import sqlalchemy as sa
revision="0001"; down_revision=None; branch_labels=None; depends_on=None
roles=("SYSTEM_ADMIN","BID_MANAGER","PROPOSAL_ENGINEER","PLANNING","ENGINEERING","CONTRACTS","COMMERCIAL","PROCUREMENT","FINANCE","MANAGEMENT_REVIEWER","READ_ONLY")
def upgrade():
 op.create_table("roles",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("name",sa.Enum(*roles,name="rolename"),nullable=False),sa.UniqueConstraint("name"))
 op.create_table("users",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("email",sa.String(255),nullable=False),sa.Column("full_name",sa.String(255),nullable=False),sa.Column("is_active",sa.Boolean(),nullable=False),sa.UniqueConstraint("email")); op.create_index("ix_users_email","users",["email"])
 op.create_table("user_roles",sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="CASCADE"),primary_key=True),sa.Column("role_id",sa.Integer(),sa.ForeignKey("roles.id",ondelete="CASCADE"),primary_key=True))
 op.create_table("bid_projects",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("bid_id",sa.String(50),nullable=False),sa.Column("tender_reference_no",sa.String(100),nullable=False),sa.Column("client",sa.String(200),nullable=False),sa.Column("tender_name",sa.String(300),nullable=False),sa.Column("contract_type",sa.String(80),nullable=False),sa.Column("project_type",sa.String(100),nullable=False),sa.Column("package_section",sa.String(200)),sa.Column("location",sa.String(200)),sa.Column("estimated_value",sa.Numeric(18,2)),sa.Column("currency",sa.String(3),nullable=False),sa.Column("tender_due_date",sa.Date(),nullable=False),sa.Column("pre_bid_meeting_date",sa.Date()),sa.Column("bid_manager",sa.String(200),nullable=False),sa.Column("co_bid_manager",sa.String(200)),sa.Column("current_stage",sa.String(80),nullable=False),sa.Column("bid_status",sa.String(40),nullable=False),sa.Column("description",sa.Text()),sa.Column("created_by",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("bid_id")); op.create_index("ix_bid_projects_bid_id","bid_projects",["bid_id"])
 op.create_table("project_memberships",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("bid_project_id",sa.Integer(),sa.ForeignKey("bid_projects.id",ondelete="CASCADE"),nullable=False),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("role",sa.String(50),nullable=False),sa.UniqueConstraint("bid_project_id","user_id",name="uq_project_member")); op.create_index("ix_project_memberships_bid_project_id","project_memberships",["bid_project_id"]);op.create_index("ix_project_memberships_user_id","project_memberships",["user_id"])
 op.create_table("bid_documents",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("bid_project_id",sa.Integer(),sa.ForeignKey("bid_projects.id",ondelete="CASCADE"),nullable=False),sa.Column("original_filename",sa.String(255),nullable=False),sa.Column("stored_filename",sa.String(255)),sa.Column("file_extension",sa.String(12),nullable=False),sa.Column("mime_type",sa.String(150),nullable=False),sa.Column("file_size",sa.Integer(),nullable=False),sa.Column("checksum",sa.String(64),nullable=False),sa.Column("storage_path",sa.String(500)),sa.Column("uploaded_by",sa.Integer(),sa.ForeignKey("users.id"),nullable=False),sa.Column("uploaded_at",sa.DateTime(timezone=True),nullable=False),sa.Column("document_status",sa.String(40),nullable=False),sa.Column("document_category",sa.String(100)),sa.Column("document_subcategory",sa.String(100)),sa.Column("information_tags",sa.JSON(),nullable=False),sa.Column("revision_no",sa.Integer(),nullable=False),sa.Column("is_latest_revision",sa.Boolean(),nullable=False),sa.Column("revision_of_document_id",sa.Integer(),sa.ForeignKey("bid_documents.id")),sa.Column("duplicate_of_document_id",sa.Integer(),sa.ForeignKey("bid_documents.id")),sa.Column("source_type",sa.String(50),nullable=False),sa.Column("notes",sa.Text()))
 for name,cols in [("ix_bid_documents_bid_project_id",["bid_project_id"]),("ix_bid_documents_checksum",["checksum"]),("ix_bid_documents_file_extension",["file_extension"]),("ix_bid_documents_uploaded_at",["uploaded_at"]),("ix_bid_documents_document_status",["document_status"]),("ix_bid_documents_document_category",["document_category"])]: op.create_index(name,"bid_documents",cols)
 op.create_table("audit_events",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id")),sa.Column("bid_project_id",sa.Integer(),sa.ForeignKey("bid_projects.id")),sa.Column("event_type",sa.String(80),nullable=False),sa.Column("entity_type",sa.String(80),nullable=False),sa.Column("entity_id",sa.String(80),nullable=False),sa.Column("timestamp",sa.DateTime(timezone=True),nullable=False),sa.Column("request_metadata",sa.JSON(),nullable=False),sa.Column("details",sa.JSON(),nullable=False));op.create_index("ix_audit_events_event_type","audit_events",["event_type"]);op.create_index("ix_audit_events_timestamp","audit_events",["timestamp"]);op.create_index("ix_audit_events_bid_project_id","audit_events",["bid_project_id"])
def downgrade():
 op.drop_table("audit_events");op.drop_table("bid_documents");op.drop_table("project_memberships");op.drop_table("bid_projects");op.drop_table("user_roles");op.drop_index("ix_users_email",table_name="users");op.drop_table("users");op.drop_table("roles")
 if op.get_bind().dialect.name=="postgresql": op.execute("DROP TYPE IF EXISTS rolename")
